// <auto-generated />
using APICinemaProject2.DAL.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APICinemaProjectV2.DAL.Migrations
{
    [DbContext(typeof(AbContext))]
    partial class AbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("APICinemaProject2.DAL.Database.Models.Actor", b =>
                {
                    b.Property<int>("ActorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActorName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActorID");

                    b.ToTable("Actors");
                });

            modelBuilder.Entity("APICinemaProject2.DAL.Models.CandyShop", b =>
                {
                    b.Property<int>("CandyShopID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CandyShopName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CandyShopPrice")
                        .HasColumnType("int");

                    b.Property<string>("CandyShopType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CandyShopID");

                    b.ToTable("CandyShops");
                });
#pragma warning restore 612, 618
        }
    }
}
